### ISSUE TITLE
what should the html template look like?

### ISSUE THREAD

**Issue by dirsceol** [wfsovereign/jsmind#1]
what should the html template look like?

**Comment by pixoft-io** [comment]
Angular 2> :
add a container with the define id name in your options container "jsmind_container" 

----- component.ts

const option = {
  container: 'jsmind_container',
  theme: 'normal',
  editable: true,
  depth: 4,
  hierarchyRule: HIERARCHY_RULES
};

----- html
.... <"div  id="jsmind_container"></div> ....


-----
pd. remember to import your css

**Comment by wfsovereign** [comment]
please see the example folder.
