### ISSUE TITLE
features

### ISSUE THREAD

**Issue by glazkovalex** [wfsovereign/jsmind#5]
is it possible to insert a node multi-line text?
is it possible to insert a node html to insert the icons, lists, tables, links, etc?

**Comment by wfsovereign** [comment]
nice feature.
insert a node html, it's a customize component, I will think about it.
but now, achieve it is hard of current framework. so, do you have any good plan? I will glad to see your pull request.

**Comment by glazkovalex** [comment]
I found out that the original component supports multiline text and html http://hizzgdev.github.io/jsmind/example/2_features.html. Lacks only the html text editor like TinyMCE, but I think it can be added on top, using jquery. Thank you for your answer.
