### ISSUE TITLE
Didnt work

### ISSUE THREAD

**Issue by jackillman** [wfsovereign/jsmind#7]
copied what is indicated in the documentation and now shows this error
ERROR in node_modules/mind-map/node_modules/rxjs/Subject.d.ts(24,5): error TS2416: Property 'lift' in type 'Subject<T>' is not assignable to the same property in base type 'Observable<T>'.
  Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
    Type 'Observable<T>' is not assignable to type 'Observable<R>'.
      Type 'T' is not assignable to type 'R'.
src/app/mindmap/mindmap.component.ts(175,20): error TS2304: Cannot find name 'customizeUtil'.

**Comment by wfsovereign** [comment]
ok, I will solve it as soon as passible

**Comment by wfsovereign** [comment]
already update, please upgrade version to 0.2.1, if there still have problems, please keep in touch
