### ISSUE TITLE
 How to implement mind map without hierarchy option?

### ISSUE THREAD

**Issue by deriknyvo** [wfsovereign/jsmind#8]
I would like to use the project but without the option of hierarchy, I tried several configurations but could not achieve the result I would like. Is it possible to use the project without the hierarchy option?

**Comment by wfsovereign** [comment]
Sorry for the late reply.
I understand what your mean is only need input box in each small module and no need for the hierarchy type? that's mean your need just sample brain map function，is my understanding correct?

**Comment by deriknyvo** [comment]
Exactly. Would like to implement without the select element within each node.
![Screenshot from 2019-10-10 16-35-56](https://user-images.githubusercontent.com/33598231/66600523-14444000-eb7c-11e9-86b3-fbf76cb0f148.png)

**Comment by wfsovereign** [comment]
Ok, I know, theoretically the type select can be without in each node, but the original intention of 
 this project is add this type for each node : )

I will make this type selector optional, maybe this weekend, hope can help you.

**Comment by wfsovereign** [comment]
The new version default view is not options, please be enjoy

**Comment by deriknyvo** [comment]
> The new version default view is not options, please be enjoy


amazing, thank you very much
